import { Inter } from "next/font/google";
import "./globals.css";
import SessionAuthProvider from "@/components/context/SessionAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
    <SessionAuthProvider>
      <body className={inter.className}>
        {children}
      </body>
    </SessionAuthProvider>
    </html>
  );
}
